# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '4c8e7db9-7472-409e-8b5a-49c63cab73e1'
  
  # Web app name
  webAppName: 'java-spring-boot'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
stages:
  - stage: Build
    jobs: 
    - job: Build
      steps:
      - task: Maven@4
        inputs:
          azureSubscription: 'Azure subscription 1(87d973c5-1ffd-45e0-8435-6f52ef9a36d9)'
          mavenPomFile: './app/pom.xml'
          goals: 'package -DskipTests'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: true
          sqMavenPluginVersionChoice: 'latest'
          checkStyleRunAnalysis: true